#!/usr/bin/env python3

import sys
import subprocess
import csv
import urllib.request
from io import StringIO
import json


FINDINGS_URL="https://raw.githubusercontent.com/code-423n4/code423n4.com/main/_data/findings/findings.csv"



if len(sys.argv) > 1:
  wardens=sys.argv[1:len(sys.argv)]
else:
  print("Usage: c4-stats <wardens...>")

response = urllib.request.urlopen(FINDINGS_URL)
csv_data = response.read()

rs = []

file = StringIO(bytes.decode(csv_data, "UTF-8"))

csvr = csv.reader(file)
headers = next(csvr, None)
for row in csvr:
  r = {}
  for i in range(0, len(headers)):
    r[headers[i]] = row[i]
  rs.append(r)

stats = { }

def ppUSD(n):
  return '${:0,.2f}'.format(round(n, 2))

# Initialize
lastContest = 0
for r in rs:
  lastContest = r["contest"]
  if r["handle"]:
    handle = r["handle"]
    if not handle in stats:
      stats[handle] = { "handle": handle, "contests": 0, "highs": 0, "mediums": 0, "qaReports": 0, "gasReports": 0, "submissions": 0, "total": 0, "lastContest": 0 }
    if lastContest != stats[handle]["lastContest"]:
      stats[handle]["contests"] += 1
      stats[handle]["lastContest"] = lastContest
    if r["finding"][0:1] == "H":
      stats[handle]["highs"] += 1
    if r["finding"][0:1] == "M":
      stats[handle]["mediums"] += 1
    if r["finding"][0:1] == "Q":
      stats[handle]["qaReports"] += 1
    if r["finding"][0:1] == "G":
      stats[handle]["gasReports"] += 1
    stats[handle]["submissions"] += 1
    stats[handle]["total"] += float(r["awardUSD"])

for h in stats.keys():
  del stats[h]["lastContest"]
  stats[h]["averagePerContest"] = ppUSD(stats[h]["total"] / stats[h]["contests"])
  stats[h]["averagePerSubmission"] = ppUSD(stats[h]["total"] / stats[h]["submissions"])
  stats[h]["total"] = ppUSD(stats[h]["total"])


# Collate results
results = []
for warden in wardens:
  if warden in stats:
    results.append(stats[warden])
  else:
    results.append({ "error" : f"Warden '{warden}' has not competed" })

## Prints the records as valid JSON

print(json.dumps(results, indent=2))


